// File generated by FlutterFire CLI.
// This file is auto-generated for your Firebase project configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6JbC573Ysu_ZrvPF4Ua2EhD8bwzqpUio',
    appId: '1:265429004049:web:YOUR_WEB_APP_ID',
    messagingSenderId: '265429004049',
    projectId: 'rexplore-61772',
    authDomain: 'rexplore-61772.firebaseapp.com',
    storageBucket: 'rexplore-61772.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvM47KHsQaFsg09B-FohWMDTRCU_BsLYQ',
    appId: '1:265429004049:android:c94a92d3d98d675b9766b0',
    messagingSenderId: '265429004049',
    projectId: 'rexplore-61772',
    storageBucket: 'rexplore-61772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvM47KHsQaFsg09B-FohWMDTRCU_BsLYQ',
    appId: '1:265429004049:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '265429004049',
    projectId: 'rexplore-61772',
    storageBucket: 'rexplore-61772.firebasestorage.app',
    iosBundleId: 'com.example.rexplore',
  );
}
